version: 3

dotenv: ["{{.ROOT_DIR}}/tasks/.env", "{{.ROOT_DIR}}/tasks/.env.{{.ENV}}"]

vars:
  NAME: worker
  PREFIX: poc_igor_orch_stepf

includes:
  go-ecs:
    taskfile: ../../../tasks/go-ecs.yml

tasks:
  build:
    cmds:
      - task: go-ecs:build
